# Generated by Django 5.1.7 on 2025-03-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='data_publicacao',
            field=models.DateTimeField(),
        ),
    ]
