# Generated by Django 5.1.7 on 2025-03-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('categoria', models.CharField(choices=[('musica', 'Musica'), ('palestra', 'Palestra'), ('workshop', 'Workshop'), ('filmes', 'Filmes')], max_length=10)),
            ],
        ),
    ]
